---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mizahom/public_html/
    - /opt/cpanel/ea-nodejs10/bin/cd repositories/mizah/
    - /opt/cpanel/ea-nodejs10/bin/npm install
    - /opt/cpanel/ea-nodejs10/bin/set NODE_ENV=production
    - /opt/cpanel/ea-nodejs10/bin/node src/index.js
