import React from 'react';
import Controls from '../../controls/Controls';

export default function SettingsForm({ values, handleInputChange, errors = {} }) {
  return (
    <>
      <Controls.Input
        label="Facebook"
        name="facebook"
        value={values.facebook}
        onChange={handleInputChange}
        error={errors.facebook}
        required
      />
      <Controls.Input
        label="Twitter"
        name="twitter"
        value={values.twitter}
        onChange={handleInputChange}
        error={errors.twitter}
        required
      />
      <Controls.Input
        label="Instagram"
        name="instagram"
        value={values.instagram}
        onChange={handleInputChange}
        error={errors.instagram}
        required
      />
      <Controls.Input
        label="Google"
        name="google"
        value={values.google}
        onChange={handleInputChange}
        error={errors.google}
      />
      <Controls.Input
        label="Website"
        name="website"
        value={values.website}
        onChange={handleInputChange}
        error={errors.website}
      />
      <Controls.Input
        label="Email"
        name="email"
        value={values.email}
        onChange={handleInputChange}
        error={errors.email}
      />
      <Controls.Input
        label="WhatsApp NO"
        name="whatsAppNo"
        value={values.whatsAppNo}
        onChange={handleInputChange}
        error={errors.whatsAppNo}
      />
      <Controls.Input
        label="WhatsApp Link"
        name="whatsAppLink"
        value={values.whatsAppLink}
        onChange={handleInputChange}
        error={errors.whatsAppLink}
      />
      <Controls.Input
        label="Address"
        name="address"
        value={values.address}
        onChange={handleInputChange}
        error={errors.address}
      />
      <Controls.Input
        label="Address Ar"
        name="addressAr"
        value={values.addressAr}
        onChange={handleInputChange}
        error={errors.addressAr}
      />
      <Controls.Input
        label="Description"
        name="description"
        value={values.description}
        onChange={handleInputChange}
        error={errors.description}
        multiline
      />
      <Controls.Input
        label="DescriptionAr"
        name="descriptionAr"
        value={values.descriptionAr}
        onChange={handleInputChange}
        error={errors.descriptionAr}
        multiline
      />
    </>
  );
}
